import axios from 'axios'
import Head from 'next/head'
import Footer from '../Components/Footer/Footer'
import Header from '../Components/Header/Header'
import HomePage from '../Components/HomePage/HomePage'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux';
import { fetchCars } from './../Redux/Slices/HomePageSlice/HomePageSlice'
import { useEffect } from 'react'
import { wrapper } from '../Redux/store/store'

export default function Home({ data,  make, model, bodyType, exteriorColor, interiorColor, transmission, driveTrain, fuelType, features }) {


  return (
    <div className='w-[100%] h-auto justify-center items-center flex'>
      <Head>
        <title>CarWig</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HomePage data={data} make={make} model={model} bodyType={bodyType} exteriorColor={exteriorColor} interiorColor={interiorColor} transmission={transmission} fuelType={fuelType} driveTrain={driveTrain} features={features} />
      </div>

    </div>
  )
}

export async function getServerSideProps() {


  const url = `https://autodigg.com/ad-api/cars/list?usedCar=true&car_type=Used+car&page=1&radius=100`
  const response = await axios.get(url)
  const data = response.data

  const makeUrl = "https://autodigg.com/ad-api/cars/list?return=make"
  const makeResponse = await axios.get(makeUrl)
  const make = makeResponse.data

  const modelUrl = "https://autodigg.com/ad-api/cars/list?make=&return=model"
  const modelResponse = await axios.get(modelUrl)
  const model = modelResponse.data

  const bodyTypeUrl = "https://autodigg.com/ad-api/cars/list?make=&model=&usedCar=true&car_type=Used+car&page=1&radius=100&year=2011%2C2021&zip=&return=body_type"
  const bodyResponse = await axios.get(bodyTypeUrl)
  const bodyType = bodyResponse.data

  const exteriorColorUrl = 'https://autodigg.com/ad-api/cars/list?body_type=&make=&model=&usedCar=true&car_type=Used+car&page=1&radius=100&year=2011%2C2021&zip=&return=exterior_color'
  const extRes = await axios.get(exteriorColorUrl)
  const exteriorColor = extRes.data

  const interiorColorUrl = 'https://autodigg.com/ad-api/cars/list?body_type=&make=&model=&usedCar=true&car_type=Used+car&page=1&radius=100&year=2011%2C2021&zip=&return=interior_color'
  const intRes = await axios.get(interiorColorUrl)
  const interiorColor = intRes.data

  const transmissionUrl = "https://autodigg.com/ad-api/cars/list?body_type=&make=&model=&usedCar=true&car_type=Used+car&page=1&radius=100&year=2011%2C2021&zip=&return=transmission"
  const transRes = await axios.get(transmissionUrl)
  const transmission = transRes.data

  const driveTrainUrl = "https://autodigg.com/ad-api/cars/list?body_type=&make=&model=&usedCar=true&car_type=Used+car&page=1&radius=100&year=2011%2C2021&zip=&return=drivetrain"
  const driveRes = await axios.get(driveTrainUrl)
  const driveTrain = driveRes.data

  const fuelTypeUrl = "https://autodigg.com/ad-api/cars/list?body_type=&make=&model=&usedCar=true&car_type=Used+car&page=1&radius=100&year=2011%2C2021&zip=&return=fuel_type"
  const fuelRes = await axios.get(fuelTypeUrl)
  const fuelType = fuelRes.data

  const featuresUrl = "https://autodigg.com/ad-api/cars/list?body_type=&make=&model=&usedCar=true&car_type=Used+car&page=1&radius=100&year=2011%2C2021&zip=&return=features"
  const fetRes = await axios.get(featuresUrl)
  const features = fetRes.data

  return {
    props: {
      data: data,
      make: make,
      model: model,
      bodyType: bodyType,
      exteriorColor: exteriorColor,
      interiorColor: interiorColor,
      transmission: transmission,
      driveTrain: driveTrain,
      fuelType: fuelType,
      features: features,


    },
  }
}



