import axios from 'axios'
import Head from 'next/head'
import HomePage from '../Components/HomePage/HomePage'

export default function Home(props) {



  return (
    <div className='w-[100%] h-auto justify-center items-center flex'>
      <Head>
        <title>CarWig</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HomePage  props={props} />
      </div>
    </div>
  )
}

  export async function getServerSideProps(){
    const init_url = "https://autodigg.com/ad-api/cars/list?usedCar=true&car_type=Certified+pre-owned,Used+car,New+car&page=1&radius=100&year=2000,2021&zip=&price_from=0&price_to=100000";
    const data = await axios.all([
      axios.get(init_url),
      axios.get(`${init_url}&return=count`),
      axios.get(`${init_url}&return=body_type`),
      axios.get(`${init_url}&return=exterior_color`),
      axios.get(`${init_url}&return=interior_color`),
      axios.get(`${init_url}&return=transmission`),
      axios.get(`${init_url}&return=drivetrain`),
      axios.get(`${init_url}&return=fuel_type`),
      axios.get(`${init_url}&return=features`),
      axios.get(`https://autodigg.com/ad-api/cars/list?return=make`),
      axios.get(`https://autodigg.com/ad-api/cars/list?make=&return=model`)
    ])
    
    

    return {
      props : {
        cars : data[0].data,
        count : data[1].data.count,
        bodyType : data[2].data,
        exteriorColor : data[3].data,
        interiorColor : data[4].data,
        transmission : data[5].data,
        dTrain : data[6].data,
        fuelType : data[7].data,
        features : data[8].data,
        make : data[9].data,
        model : data[10].data,
      }
    }

  }




  
// export const getServerSideProps = wrapper.getServerSideProps(
//   (store) => async () => {

  // store.dispatch(getCars(data[0].data));
    // store.dispatch(getCount(data[1].data.count))
    // store.dispatch(getBodyType(data[2].data ? data[2].data : null))
    // store.dispatch(getExteriorColor(data[3].data))
    // store.dispatch(getInteriorColor(data[4].data))
    // store.dispatch(getTransmission(data[5].data))
    // store.dispatch(getDriveTrain(data[6].data))
    // store.dispatch(getFuelType(data[7].data))
    // store.dispatch(getFeatures(data[8].data))
    // store.dispatch(getMake(data[9].data))
    // store.dispatch(getModel(data[10].data))